-- Create scans table for storing 7-digit QR codes
CREATE TABLE public.scans (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code BIGINT NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.scans ENABLE ROW LEVEL SECURITY;

-- Allow public read access (no auth required for this simple app)
CREATE POLICY "Anyone can view scans"
  ON public.scans
  FOR SELECT
  USING (true);

-- Allow public insert access
CREATE POLICY "Anyone can insert scans"
  ON public.scans
  FOR INSERT
  WITH CHECK (true);

-- Enable realtime for the scans table
ALTER PUBLICATION supabase_realtime ADD TABLE public.scans;