-- ============================================
-- Create teams table
-- ============================================
CREATE TABLE IF NOT EXISTS public.teams (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id uuid UNIQUE NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
  team INTEGER NOT NULL CHECK (team >= 1 AND team <= 10),
  created_at TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()
);

-- Enable Row Level Security
ALTER TABLE public.teams ENABLE ROW LEVEL SECURITY;

-- RLS Policies
CREATE POLICY "Users can view all teams"
  ON public.teams
  FOR SELECT
  USING (auth.uid() IS NOT NULL);

CREATE POLICY "Users can insert their own team"
  ON public.teams
  FOR INSERT
  WITH CHECK (auth.uid() = user_id);

CREATE POLICY "Users can update their own team"
  ON public.teams
  FOR UPDATE
  USING (auth.uid() = user_id);

-- Create index for team lookups
CREATE INDEX IF NOT EXISTS idx_teams_team ON public.teams(team);

-- ============================================
-- Update scan_with_profile view to include team
-- ============================================
-- Drop the existing view first (required when changing column structure)
DROP VIEW IF EXISTS public.scan_with_profile;

-- Recreate view with team column
CREATE VIEW public.scan_with_profile AS
SELECT
  s.id,
  s.code,
  s.user_id,
  p.username,
  t.team,
  s.created_at
FROM public.scans s
LEFT JOIN public.profiles p ON p.id = s.user_id
LEFT JOIN public.teams t ON t.user_id = s.user_id
ORDER BY s.created_at DESC;

-- Grant access to authenticated users
GRANT SELECT ON public.scan_with_profile TO authenticated;